version: '3'

services:

  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: blocks-php
    working_dir: /var/www/blocks-api
    volumes:
      - ./:/var/www/blocks-api
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - blocks-network

  webserver:
    image: nginx:1.20
    container_name: blocks-api-webserver
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/blocks-api
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - blocks-network

  db:
    image: mysql:5.7
    container_name: blocks-db
    ports:
      - "3006:3306"
    environment:
      MYSQL_DATABASE: blocks
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - blocks-data:/var/lib/mysql/
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./.docker/mysql/blocks.sql:/backups/blocks.sql
    networks:
      - blocks-network

networks: 
    blocks-network:

volumes: 
   blocks-data: